[package]
name = "atci-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
confy = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
globset = "0.4"
walkdir = "2.0"
chrono = { version = "0.4", features = ["serde"] }
